version: '3'

services:
  vector_storage:
    image: ankane/pgvector
    container_name: vector_storage
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres

    volumes:
      - .docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  memory_storage:
    image: mongo
    container_name: memory_storage
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
